const { askClaude } = require("../providers/claude/claude.provider");
const { prompt } = require("inquirer");
const ApiProvider = require("../providers/api-provider");
const { setEnvVar, getEnvVar } = require("./env.util");

/**
 * @function tryAskLLM
 * @param {string} type The type of prompt to send to AI (e.g. 'component' or 'worker')
 * @description Tries to ask AI with a prompt to generate code
 * @returns {string} The code generated by AI or undefined if the user chose not to use AI
 */
async function tryAskLLM(type = 'component') {
    // Prompt user if they want to give a description to claude
    let codeResult;
    let defaultProvider = await getEnvVar('DEFAULT_AI_PROVIDER');
    if (!defaultProvider) {
        defaultProvider = 'claude';
        await setEnvVar('DEFAULT_AI_PROVIDER', defaultProvider);
    }
    const { codePrompt } = await prompt([
        {
            type: 'input',
            name: 'codePrompt',
            message: `\nPrompt for generating code w/${defaultProvider}? (ignore and press ENTER to not use AI)\n\n`,
        },
    ]);
    if (codePrompt) {
        const isSet = await ApiProvider.isApiKeySet(vendor);
        if (!isSet) {
            const { apiKey } = await prompt([
                {
                    type: 'password',
                    name: 'apiKey',
                    message: `\n${defaultProvider} API Key not set! Provide one below or ignore to create the component anyways.\n\n`,
                },
            ]);
            if (apiKey) {
                await ApiProvider.setApiKey(apiKey);
            } else {
                console.log(`\n${defaultProvider}  API Key not set. Generating component without AI`);
                return;
            }
        }
        const key = await ApiProvider.getApiKey(vendor);

        switch (defaultProvider) {
            case 'claude':
            default:
                codeResult = await askClaude(codePrompt, type, key);
                break;
        }
    }

    return codeResult;
}

module.exports = {tryAskLLM};